# Generated by Django 5.2.6 on 2025-10-13 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Категория турнира')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория турнира',
                'verbose_name_plural': 'Категории турниров',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team1_score',
            field=models.IntegerField(default=0, verbose_name='Счёт команды 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_score',
            field=models.IntegerField(default=0, verbose_name='Счёт команды 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.team', verbose_name='Победитель'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentcategory', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
