# Generated by Django 5.2.6 on 2025-12-11 12:02
import pyotp
import tqdm

from django.db import migrations, models

def fill_totp_field(apps, schema_editor):
    UserProfile = apps.get_model("tournaments", "Player")
    for u in tqdm.tqdm(UserProfile.objects.all()):
        u.totp_key = pyotp.random_hex()
        u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='totp_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RunPython(fill_totp_field),
    ]
