# Generated by Django 5.2.6 on 2025-10-30 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_player_photo_team_logo_alter_player_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswordInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_password', models.CharField(max_length=50, verbose_name='Изначальный пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Информация о пароле',
                'verbose_name_plural': 'Информация о паролях',
            },
        ),
    ]
