# Generated by Django 5.2.6 on 2025-10-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_userpasswordinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPasswordInfo',
        ),
    ]
